"""Canonical judge-facing plan views.

The primary pairwise view strips provenance/source identity and presentation-heavy
LLM prose while preserving the week structure required by compare_plans.
"""
from __future__ import annotations

import re
from typing import Any

PRESENTATION_HEAVY_KEYS = {
    "citations",
    "claim_attributions",
    "data_notes",
    "readiness_rationale",
    "recovery_rationale",
    "rationale",
    "explanation",
    "explanations",
    "reasoning",
    "notes",
    "snapshot_notes",
    "risk_message",
    "source_model",
    "arm",
    "generation_condition",
    "generation_pipeline",
    "runtime_backend",
    "runtime_metadata",
    "explainer_model",
    "actual_explainer_model",
    "explainer_model_verified",
}


def _scrub_text(value: Any) -> Any:
    if not isinstance(value, str):
        return value
    text = re.sub(r"synthetic fixture generated by fixtures/build\.py", "synthetic athlete fixture", value, flags=re.I)
    text = re.sub(r"generated\s+by\s+fixtures/build\.py", "from a synthetic athlete fixture", text, flags=re.I)
    text = re.sub(r"\bQwen(?:/[A-Za-z0-9_.\-]+)?", "model", text, flags=re.I)
    text = re.sub(r"\bGemma(?:/[A-Za-z0-9_.\-]+)?", "model", text, flags=re.I)
    text = re.sub(r"\bprogrammatic\b", "control", text, flags=re.I)
    return text


def _truncate(value: Any, limit: int) -> str:
    text = str(_scrub_text(value) or "").strip()
    text = re.sub(r"\s+", " ", text)
    if len(text) <= limit:
        return text
    return text[: max(0, limit - 1)].rstrip() + "…"


def _session_type(day: dict[str, Any]) -> str:
    return str(day.get("session_type") or "").strip().lower()


def canonicalize_plan_for_pairwise(plan: dict[str, Any]) -> dict[str, Any]:
    days = list(((plan.get("plan") or {}).get("days") or []))
    canonical_days: list[dict[str, Any]] = []
    for idx, day in enumerate(days):
        if not isinstance(day, dict):
            continue
        canonical_days.append(
            {
                "day_index": int(day.get("day_index") or day.get("day") or idx + 1),
                "session_type": _session_type(day),
                "duration_minutes": int(float(day.get("duration_minutes") or 0)),
                "is_rest_day": bool(day.get("is_rest_day", False)),
                "is_hard_day": bool(day.get("is_hard_day", False)),
                "target_intensity": str(day.get("target_intensity") or "").strip().lower(),
                "workout": _truncate(day.get("workout"), 140),
                "purpose": _truncate(day.get("purpose"), 100),
            }
        )
    return {
        "plan": {
            "days": canonical_days,
            "summary": {
                "plan_days": len(canonical_days),
                "total_minutes": sum(int(day.get("duration_minutes") or 0) for day in canonical_days),
                "rest_days": sum(1 for day in canonical_days if day.get("is_rest_day")),
                "hard_days": sum(1 for day in canonical_days if day.get("is_hard_day")),
                "long_runs": sum(1 for day in canonical_days if day.get("session_type") == "long"),
            },
        },
        "judge_view": "canonical_masked_structural_v1",
    }


def canonicalize_pair_for_pairwise(plan_a: dict[str, Any], plan_b: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    return canonicalize_plan_for_pairwise(plan_a), canonicalize_plan_for_pairwise(plan_b)
"""judge/canonicalize.py — fixed-format pairwise rendering helpers."""
from __future__ import annotations

import copy
from typing import Any

_ALLOWED_SESSION_KEYS = (
    "date",
    "session_type",
    "is_rest_day",
    "is_hard_day",
    "duration_minutes",
    "target_intensity",
    "terrain",
)


def _canonical_day(day: dict[str, Any], idx: int) -> dict[str, Any]:
    rendered = {key: day.get(key) for key in _ALLOWED_SESSION_KEYS}
    rendered["day_index"] = idx + 1
    rendered["signal_count"] = len(day.get("signal_ids") or [])
    return rendered


def _risk_kinds(plan_obj: dict[str, Any]) -> list[str]:
    kinds: list[str] = []
    for risk in plan_obj.get("risks") or []:
        if not isinstance(risk, dict):
            continue
        kind = str(risk.get("kind") or risk.get("type") or "").strip()
        if kind:
            kinds.append(kind)
    return sorted(set(kinds))


def canonicalize_plan_for_pairwise(plan_obj: dict[str, Any]) -> dict[str, Any]:
    obj = copy.deepcopy(plan_obj)
    days = ((obj.get("plan") or {}).get("days") or [])
    canonical_days = [_canonical_day(day if isinstance(day, dict) else {}, idx) for idx, day in enumerate(days)]

    readiness = obj.get("readiness") or {}
    plan = obj.get("plan") or {}

    return {
        "meta": {
            "style": ((obj.get("meta") or {}).get("style") or ""),
            "primary_goal": ((obj.get("meta") or {}).get("primary_goal") or ""),
        },
        "plan": {
            "weekly_totals": copy.deepcopy(plan.get("weekly_totals") or {}),
            "days": canonical_days,
        },
        "readiness": {
            "status": readiness.get("status"),
            "signal_count": len(readiness.get("signal_ids") or []),
        },
        "risk_summary": {
            "n_risks": len(obj.get("risks") or []),
            "risk_kinds": _risk_kinds(obj),
        },
        "data_note_count": len(obj.get("data_notes") or []),
        "citation_count": len(obj.get("citations") or []),
        "claim_attribution_count": len(obj.get("claim_attributions") or []),
    }


def canonicalize_pair_for_pairwise(plan_a: dict[str, Any], plan_b: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    return canonicalize_plan_for_pairwise(plan_a), canonicalize_plan_for_pairwise(plan_b)
