"""tests/mock_llm_client.py — dummy OpenAI-compatible client.

Returns schema-valid JSON for every trailtraining call so Gate-0 tests run
without a GPU, an API key, or network access.

The mock inspects the schema name embedded in the call kwargs (via
``text.format.name`` or ``response_format.json_schema.name``) and returns a
minimal but contract-passing payload for each schema variant.
"""
from __future__ import annotations

import datetime as dt
import json
from typing import Any


class _FakeResponse:
    """Minimal stand-in for a responses-style structured output."""

    def __init__(self, text: str) -> None:
        self.output_text = text


class _FakeChatMessage:
    def __init__(self, text: str, parsed: Any) -> None:
        self.content = text
        self.parsed = parsed
        self.refusal = None


class _FakeChatChoice:
    def __init__(self, text: str, parsed: Any) -> None:
        self.message = _FakeChatMessage(text, parsed)


class _FakeChatResponse:
    """Minimal stand-in for an OpenAI chat-completions structured output."""

    def __init__(self, text: str, parsed: Any) -> None:
        self.choices = [_FakeChatChoice(text, parsed)]
        self.output_text = text


class MockLLMClient:
    """Drop-in replacement for ``openai.OpenAI`` used by trailtraining.

    Supports both:
      - client.responses.create(**kwargs)
      - client.chat.completions.create(**kwargs)
    """

    def __init__(self) -> None:
        self.responses = _ResponsesNamespace()
        self.chat = _ChatNamespace()


class _ResponsesNamespace:
    def create(self, **kwargs: Any) -> _FakeResponse:
        schema_name = _extract_schema_name(kwargs)
        payload = _build_payload(schema_name)
        return _FakeResponse(json.dumps(payload, default=str))


class _ChatNamespace:
    def __init__(self) -> None:
        self.completions = _ChatCompletionsNamespace()


class _ChatCompletionsNamespace:
    def create(self, **kwargs: Any) -> _FakeChatResponse:
        schema_name = _extract_schema_name(kwargs)
        payload = _build_payload(schema_name)
        text = json.dumps(payload, default=str)
        return _FakeChatResponse(text, payload)


def _extract_schema_name(kwargs: dict[str, Any]) -> str:
    """Pull the JSON schema name from any of the structured-output call forms."""
    text = kwargs.get("text") or {}
    fmt = text.get("format") or {}
    if fmt.get("name"):
        return str(fmt["name"])

    rf = kwargs.get("response_format") or {}
    js = rf.get("json_schema") or {}
    if js.get("name"):
        return str(js["name"])

    return ""


_TODAY = "2026-03-17"
_PLAN_START = "2026-03-18"

_SNAPSHOT = {
    "distance_km": "30",
    "moving_time_hours": "4.0",
    "elevation_m": "500",
    "activity_count": "5",
    "sleep_hours_mean": "7.5",
    "hrv_mean": "68",
    "rhr_mean": "46",
}


def _training_plan_payload() -> dict[str, Any]:
    return {
        "meta": {
            "today": _TODAY,
            "plan_start": _PLAN_START,
            "plan_days": 7,
            "style": "trailrunning",
            "primary_goal": "to become a faster trail runner",
            "lifestyle_notes": "",
        },
        "snapshot": {
            "last7": dict(_SNAPSHOT),
            "baseline28": dict(_SNAPSHOT),
            "notes": "Mock snapshot",
        },
        "readiness": {
            "status": "steady",
            "rationale": "Mock rationale based on available data.",
            "signal_ids": ["forecast.readiness.status"],
        },
        "plan": {
            "weekly_totals": {
                "planned_distance_km": None,
                "planned_moving_time_hours": 4.0,
                "planned_elevation_m": None,
            },
            "days": _make_plan_days(7),
        },
        "recovery": {
            "actions": ["Sleep 8 hours.", "Stay hydrated."],
            "signal_ids": ["forecast.readiness.status"],
        },
        "risks": [
            {
                "severity": "low",
                "message": "Monitor fatigue after the quality session.",
                "signal_ids": ["forecast.overreach_risk.level"],
            }
        ],
        "data_notes": ["Mock data generated by MockLLMClient."],
        "citations": [
            {
                "citation_id": "c1",
                "signal_id": "forecast.readiness.status",
                "source": "readiness_and_risk_forecast.json:result.readiness.status",
                "date_range": f"{_TODAY}..{_TODAY}",
                "value": "steady",
            },
            {
                "citation_id": "c2",
                "signal_id": "forecast.overreach_risk.level",
                "source": "readiness_and_risk_forecast.json:result.overreach_risk.level",
                "date_range": f"{_TODAY}..{_TODAY}",
                "value": "low",
            },
        ],
        "claim_attributions": [
            {
                "claim_id": "cl1",
                "field_path": "readiness.rationale",
                "claim_text": "Mock rationale based on available data.",
                "signal_ids": ["forecast.readiness.status"],
                "citation_ids": ["c1"],
                "support_level": "supported",
            }
        ],
        "effective_constraints": {
            "allowed_week1_hours": None,
            "effective_max_ramp_pct": 10.0,
            "effective_max_hard_per_7d": 3,
            "effective_max_consecutive_hard": 2,
            "min_rest_per_7d": 1,
            "readiness_status": "steady",
            "overreach_risk_level": "low",
            "recovery_capability_key": "load_only",
            "lifestyle_notes": "",
            "reasons": [],
        },
    }


def _make_plan_days(n: int) -> list[dict[str, Any]]:
    session_cycle = [
        ("easy", False, False, 45),
        ("tempo", False, True, 50),
        ("easy", False, False, 40),
        ("rest", True, False, 0),
        ("long", False, False, 90),
        ("aerobic", False, False, 40),
        ("strength", False, False, 30),
    ]
    days = []
    base = dt.date(2026, 3, 18)
    for i in range(n):
        st, is_rest, is_hard, dur = session_cycle[i % len(session_cycle)]
        day = base + dt.timedelta(days=i)
        days.append(
            {
                "date": day.isoformat(),
                "title": st.capitalize() + " session",
                "session_type": st,
                "is_rest_day": is_rest,
                "is_hard_day": is_hard,
                "duration_minutes": dur,
                "target_intensity": "rest" if is_rest else ("threshold" if is_hard else "easy"),
                "terrain": "n/a" if is_rest else "trail",
                "workout": "Rest day. No structured training." if is_rest else f"{dur} min {st} session.",
                "purpose": "Recovery." if is_rest else "Build aerobic base.",
                "signal_ids": ["forecast.readiness.status"],
                "estimated_distance_km": None,
                "estimated_elevation_m": None,
            }
        )
    return days


def _machine_plan_payload() -> dict[str, Any]:
    return {
        "meta": {
            "today": _TODAY,
            "plan_start": _PLAN_START,
            "plan_days": 7,
            "style": "trailrunning",
            "primary_goal": "to become a faster trail runner",
            "lifestyle_notes": "",
        },
        "readiness": {"status": "steady"},
        "plan": {
            "weekly_totals": {
                "planned_distance_km": None,
                "planned_moving_time_hours": 4.0,
                "planned_elevation_m": None,
            },
            "days": _make_machine_days(7),
        },
    }


def _make_machine_days(n: int) -> list[dict[str, Any]]:
    session_cycle = [
        ("easy", False, False, 45),
        ("tempo", False, True, 50),
        ("easy", False, False, 40),
        ("rest", True, False, 0),
        ("long", False, False, 90),
        ("aerobic", False, False, 40),
        ("strength", False, False, 30),
    ]
    days = []
    base = dt.date(2026, 3, 18)
    for i in range(n):
        st, is_rest, is_hard, dur = session_cycle[i % len(session_cycle)]
        day = base + dt.timedelta(days=i)
        days.append(
            {
                "date": day.isoformat(),
                "session_type": st,
                "is_rest_day": is_rest,
                "is_hard_day": is_hard,
                "duration_minutes": dur,
                "target_intensity": "rest" if is_rest else ("threshold" if is_hard else "easy"),
                "terrain": "n/a" if is_rest else "trail",
                "workout": "Rest day. No structured training." if is_rest else f"{dur} min {st}.",
                "estimated_distance_km": None,
                "estimated_elevation_m": None,
            }
        )
    return days


def _plan_explanation_stage_payload() -> dict[str, Any]:
    """Matches trailtraining_plan_explanation_stage_v1.

    Snapshot is now deterministic downstream, so the stage payload must NOT
    include a snapshot field.
    """
    return {
        "readiness_rationale": "Readiness looks steady based on available signals.",
        "readiness_signal_ids": ["forecast.readiness.status"],
        "day_explanations": [
            {
                "date": (dt.date(2026, 3, 18) + dt.timedelta(days=i)).isoformat(),
                "title": "Mock day",
                "purpose": "Build aerobic fitness.",
                "signal_ids": ["forecast.readiness.status"],
            }
            for i in range(7)
        ],
        "recovery": {
            "actions": ["Sleep 8 hours."],
            "signal_ids": ["forecast.readiness.status"],
        },
        "risks": [],
        "data_notes": ["Mock explanation."],
    }


def _plan_explanation_payload() -> dict[str, Any]:
    payload = {
        "snapshot": {
            "last7": dict(_SNAPSHOT),
            "baseline28": dict(_SNAPSHOT),
            "notes": "Mock explanation snapshot.",
        },
        **_plan_explanation_stage_payload(),
    }
    payload["citations"] = [
        {
            "citation_id": "c1",
            "signal_id": "forecast.readiness.status",
            "source": "forecast",
            "date_range": f"{_TODAY}..{_TODAY}",
            "value": "steady",
        }
    ]
    payload["claim_attributions"] = []
    return payload


def _compare_plans_payload() -> dict[str, Any]:
    return {
        "preferred": "plan_b",
        "reasoning": "Mock: plan B is slightly more specific.",
        "plan_a_advantages": ["More conservative."],
        "plan_b_advantages": ["More specific session purposes."],
    }


def _soft_eval_payload() -> dict[str, Any]:
    return {
        "summary": "Mock assessment: plan is coherent and goal-aligned.",
        "confidence": "medium",
        "rubric_scores": {
            rid: {"score": 80, "reasoning": "Mock."}
            for rid in [
                "goal_alignment",
                "plan_coherence",
                "explanation_quality",
                "caution_proportionality",
                "actionability",
            ]
        },
        "marker_results": [],
        "strengths": ["Clear structure."],
        "concerns": [],
        "suggested_improvements": ["Add more specific terrain cues."],
    }


def _batch_markers_payload() -> dict[str, Any]:
    try:
        from trailtraining.llm.rubrics import get_default_rubrics

        results = []
        for rubric in get_default_rubrics("trailrunning"):
            for marker in rubric.markers:
                results.append(
                    {
                        "rubric": rubric.rubric_id,
                        "marker_id": marker.marker_id,
                        "marker": marker.label,
                        "observation": "Mock observation: plan looks reasonable.",
                        "verdict": "partial",
                        "score": 3.0,
                        "evidence": "Mock evidence from plan structure.",
                        "improvement_hint": "Mock hint: add more specificity.",
                    }
                )
        return {"marker_results": results}
    except Exception:
        return {
            "marker_results": [
                {
                    "rubric": "goal_alignment",
                    "marker_id": "goal_specificity",
                    "marker": "Goal specificity",
                    "observation": "Mock.",
                    "verdict": "partial",
                    "score": 3.0,
                    "evidence": "Mock.",
                    "improvement_hint": "Mock.",
                }
            ]
        }


def _synthesis_payload() -> dict[str, Any]:
    return {
        "summary": "Mock synthesis.",
        "confidence": "medium",
        "strengths": ["Good plan."],
        "concerns": [],
        "suggested_improvements": [],
    }


_SCHEMA_DISPATCH: dict[str, Any] = {
    "trailtraining_training_plan_v4": _training_plan_payload,
    "trailtraining_machine_plan_v2": _machine_plan_payload,
    "trailtraining_plan_explanation_stage_v1": _plan_explanation_stage_payload,
    "trailtraining_plan_explanation_v1": _plan_explanation_payload,
    "trailtraining_compare_plans_v1": _compare_plans_payload,
    "trailtraining_soft_quality_assessment_v1": _soft_eval_payload,
    "trailtraining_soft_eval_synthesis_v1": _synthesis_payload,
}


def _build_payload(schema_name: str) -> dict[str, Any]:
    if schema_name.startswith("trailtraining_batch_"):
        return _batch_markers_payload()
    factory = _SCHEMA_DISPATCH.get(schema_name)
    if factory is not None:
        return factory()
    return _compare_plans_payload()
