#!/usr/bin/env python3
import argparse
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


MARKERS = {
    "plan_coherence": (
        "Overall training-plan coherence: whether the week fits together as a coherent training plan, "
        "with compatible sessions, sensible sequencing, and no internal contradictions."
    ),
    "training_specificity": (
        "Specificity to the athlete and trail-running context: terrain, hills, long-run needs, race phase, "
        "and appropriate trail/endurance demands."
    ),
    "load_progression": (
        "Appropriateness of training load and progression: total volume, session duration, stress distribution, "
        "and whether the plan avoids abrupt or excessive load."
    ),
    "recovery_safety": (
        "Recovery, rest, and safety: rest-day placement, hard-day spacing, injury-risk control, and avoidance "
        "of unsafe combinations."
    ),
    "quality_session_design": (
        "Design of quality sessions: workouts such as intervals, tempo, hills, progression runs, or long runs "
        "are purposeful, specific, and feasible."
    ),
    "endurance_development": (
        "Support for aerobic/endurance development: easy volume, long-run stimulus, sustainable aerobic work, "
        "and endurance-oriented structure."
    ),
    "readiness_alignment": (
        "Alignment with readiness/recovery constraints: whether the plan respects the athlete's readiness, "
        "recovery capacity, and fatigue constraints."
    ),
    "clarity_actionability": (
        "Clarity and actionability: whether the athlete can understand and execute the plan without ambiguity."
    ),
    "explanation_quality": (
        "Quality of explanation/rationale: whether the stated purpose and explanation are helpful, specific, "
        "and support the plan. This marker is presentation-sensitive."
    ),
}


SYSTEM_PROMPT = """You are an expert running coach and careful evaluator.

You will compare two anonymized training plans, Plan A and Plan B.
The plans have been source-masked. Do not infer or mention whether either plan was generated by a model, a program, or a human.

Evaluate each marker independently. For every marker, choose:
- "plan_a" if Plan A is better on that marker,
- "plan_b" if Plan B is better on that marker,
- "tie" if they are meaningfully equivalent.

Use only the visible plan content. Do not use source labels, file names, IDs, or provenance.
Return valid JSON only. No markdown.
"""


def compact_json(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def build_prompt(judge_input: Dict[str, Any]) -> str:
    marker_lines = "\n".join(f"- {k}: {v}" for k, v in MARKERS.items())
    schema = {
        "markers": {
            marker: {
                "preferred": "plan_a | plan_b | tie",
                "plan_a_score": "integer 1-5",
                "plan_b_score": "integer 1-5",
                "confidence": "number 0.0-1.0",
                "rationale": "brief reason, max 18 words",
            }
            for marker in MARKERS
        },
        "overall_marker_summary": "one short sentence",
    }
    return (
        "Compare Plan A and Plan B on the following markers.\n\n"
        f"MARKERS:\n{marker_lines}\n\n"
        "Scoring guidance:\n"
        "- Scores are 1 to 5, where 5 is best.\n"
        "- The preferred plan should normally be the one with the higher score.\n"
        "- Use tie when differences are negligible.\n"
        "- Keep rationales short.\n\n"
        f"REQUIRED JSON SCHEMA:\n{compact_json(schema)}\n\n"
        f"PLAN INPUT:\n{compact_json(judge_input)}\n"
    )


def get_model_from_judge(judge_name: str) -> str:
    override = os.environ.get("JUDGE_MODEL")
    if override:
        return override
    try:
        from judge.panel import get_judge  # type: ignore

        j = get_judge(judge_name)
        for attr in ("model", "model_id", "repo_id", "hf_model", "name"):
            value = getattr(j, attr, None)
            if isinstance(value, str) and value:
                return value
    except Exception:
        pass
    return judge_name


def api_base_from_env() -> str:
    for key in ("OPENAI_BASE_URL", "OPENAI_API_BASE", "VLLM_API_BASE"):
        if os.environ.get(key):
            return os.environ[key].rstrip("/")
    port = os.environ.get("VLLM_PORT", "8000")
    return f"http://127.0.0.1:{port}/v1"


def post_chat_completion(
    *,
    api_base: str,
    model: str,
    messages: List[Dict[str, str]],
    temperature: float,
    max_tokens: int,
    timeout_s: int,
) -> str:
    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "response_format": {"type": "json_object"},
    }
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{api_base.rstrip('/')}/chat/completions",
        data=data,
        headers={"Content-Type": "application/json", "Authorization": "Bearer dummy"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout_s) as resp:
        obj = json.loads(resp.read().decode("utf-8"))
    return obj["choices"][0]["message"]["content"]


def extract_json(text: str) -> Dict[str, Any]:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Strip common markdown fences.
    text2 = re.sub(r"^```(?:json)?", "", text.strip(), flags=re.I).strip()
    text2 = re.sub(r"```$", "", text2.strip()).strip()
    try:
        return json.loads(text2)
    except json.JSONDecodeError:
        pass

    # Last-resort brace extraction.
    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        return json.loads(text[start : end + 1])
    raise ValueError("Could not parse JSON response")


def normalize_marker_result(raw: Dict[str, Any]) -> Dict[str, Any]:
    markers = raw.get("markers")
    if not isinstance(markers, dict):
        raise ValueError("Response missing markers object")

    out: Dict[str, Any] = {}
    for marker in MARKERS:
        m = markers.get(marker)
        if not isinstance(m, dict):
            raise ValueError(f"Missing marker {marker}")

        def score(name: str) -> Optional[int]:
            try:
                v = int(float(m.get(name)))
            except Exception:
                return None
            if v < 1:
                v = 1
            if v > 5:
                v = 5
            return v

        plan_a_score = score("plan_a_score")
        plan_b_score = score("plan_b_score")

        preferred_raw = str(m.get("preferred", "")).strip().lower()
        preferred = preferred_raw
        if preferred in {"a", "plan a", "plana"}:
            preferred = "plan_a"
        if preferred in {"b", "plan b", "planb"}:
            preferred = "plan_b"
        if preferred in {"", "none", "null", "n/a", "na"}:
            preferred = ""

        normalization_warnings = []
        if preferred not in {"plan_a", "plan_b", "tie"}:
            if plan_a_score is not None and plan_b_score is not None:
                if plan_a_score > plan_b_score:
                    preferred = "plan_a"
                elif plan_b_score > plan_a_score:
                    preferred = "plan_b"
                else:
                    preferred = "tie"
                normalization_warnings.append(
                    f"repaired_preferred_from_scores: raw={preferred_raw!r}"
                )
            else:
                preferred = "tie"
                normalization_warnings.append(
                    f"repaired_preferred_to_tie_without_scores: raw={preferred_raw!r}"
                )

        try:
            confidence = float(m.get("confidence", 0.0))
        except Exception:
            confidence = 0.0
        confidence = max(0.0, min(1.0, confidence))

        out_marker = {
            "preferred": preferred,
            "plan_a_score": plan_a_score,
            "plan_b_score": plan_b_score,
            "confidence": confidence,
            "rationale": str(m.get("rationale", ""))[:500],
        }
        if normalization_warnings:
            out_marker["normalization_warnings"] = normalization_warnings

        out[marker] = out_marker

    return {
        "markers": out,
        "overall_marker_summary": str(raw.get("overall_marker_summary", ""))[:1000],
    }


def read_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def existing_record_ids(path: Path) -> set:
    ids = set()
    if not path.exists():
        return ids
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            try:
                ids.add(json.loads(line)["record_id"])
            except Exception:
                continue
    return ids


def role_for_plan(row: Dict[str, Any], plan_key: str) -> str:
    if plan_key == "plan_a":
        return row.get("left_plan_role") or ("llm" if row.get("order") == "AB" else "programmatic")
    if plan_key == "plan_b":
        return row.get("right_plan_role") or ("programmatic" if row.get("order") == "AB" else "llm")
    return "tie"


def enrich_marker_winners(row: Dict[str, Any], marker_obj: Dict[str, Any]) -> Dict[str, Any]:
    markers = marker_obj["markers"]
    enriched = {}
    for marker, m in markers.items():
        preferred = m["preferred"]
        winner_role = "tie" if preferred == "tie" else role_for_plan(row, preferred)
        enriched[marker] = {
            **m,
            "winner_role": winner_role,
            "llm_won": True if winner_role == "llm" else False if winner_role == "programmatic" else None,
        }
    return {**marker_obj, "markers": enriched}


def output_name(judge_name: str, temperature: float) -> str:
    temp_tag = f"t{int(round(temperature * 100)):03d}"
    return f"marker_{judge_name}_canonical_masked_scrubbed_v1_{temp_tag}.jsonl"


def failure_name(judge_name: str, temperature: float) -> str:
    temp_tag = f"t{int(round(temperature * 100)):03d}"
    return f"failures_marker_{judge_name}_canonical_masked_scrubbed_v1_{temp_tag}.jsonl"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=os.environ.get("MANIFEST"))
    ap.add_argument("--output-dir", default=os.environ.get("OUTPUT_DIR"))
    ap.add_argument("--judge", "--judge-name", dest="judge_name", default=os.environ.get("JUDGE_NAME"))
    ap.add_argument("--temperature", type=float, default=float(os.environ.get("JUDGE_TEMPERATURE", "0.0")))
    ap.add_argument("--api-base", default=None)
    ap.add_argument("--model", default=None)
    ap.add_argument("--max-tokens", type=int, default=int(os.environ.get("MARKER_MAX_TOKENS", "768")))
    ap.add_argument("--timeout-s", type=int, default=int(os.environ.get("MARKER_TIMEOUT_S", "600")))
    ap.add_argument("--sleep-s", type=float, default=float(os.environ.get("MARKER_SLEEP_S", "0.0")))
    args, _unknown = ap.parse_known_args()

    if not args.manifest:
        raise SystemExit("Missing --manifest or MANIFEST")
    if not args.output_dir:
        raise SystemExit("Missing --output-dir or OUTPUT_DIR")
    if not args.judge_name:
        raise SystemExit("Missing --judge/--judge-name or JUDGE_NAME")

    manifest = Path(args.manifest)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    api_base = (args.api_base or api_base_from_env()).rstrip("/")
    model = args.model or get_model_from_judge(args.judge_name)

    out_path = output_dir / output_name(args.judge_name, args.temperature)
    fail_path = output_dir / failure_name(args.judge_name, args.temperature)

    rows = [r for r in read_jsonl(manifest) if r.get("judge") == args.judge_name]
    done = existing_record_ids(out_path)

    print(f"marker_runner judge={args.judge_name} model={model} api_base={api_base}", flush=True)
    print(f"manifest_rows_for_judge={len(rows)} already_done={len(done)} output={out_path}", flush=True)

    wrote = 0
    failures = 0

    with out_path.open("a", encoding="utf-8") as out_f, fail_path.open("a", encoding="utf-8") as fail_f:
        for i, row in enumerate(rows):
            rid = row["record_id"]
            if rid in done:
                continue

            try:
                judge_input_path = Path(row["judge_input_path"])
                judge_input = json.loads(judge_input_path.read_text(encoding="utf-8"))
                prompt = build_prompt(judge_input)

                messages = [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ]

                content = post_chat_completion(
                    api_base=api_base,
                    model=model,
                    messages=messages,
                    temperature=args.temperature,
                    max_tokens=args.max_tokens,
                    timeout_s=args.timeout_s,
                )
                parsed = normalize_marker_result(extract_json(content))
                parsed = enrich_marker_winners(row, parsed)

                output_row = {
                    "record_id": rid,
                    "pair_id": row.get("pair_id"),
                    "judge": row.get("judge"),
                    "judge_model_family": row.get("judge_model_family"),
                    "source_model_family": row.get("source_model_family"),
                    "self_family_match": row.get("self_family_match"),
                    "fixture_id": row.get("fixture_id"),
                    "order": row.get("order"),
                    "position": row.get("position"),
                    "run": row.get("run"),
                    "left_plan_role": row.get("left_plan_role"),
                    "right_plan_role": row.get("right_plan_role"),
                    "llm_plan_id": row.get("llm_plan_id"),
                    "programmatic_plan_id": row.get("programmatic_plan_id"),
                    "structural_score_gap": row.get("structural_score_gap"),
                    "structural_score_version": row.get("structural_score_version"),
                    "canonical_masking_version": row.get("canonical_masking_version"),
                    "judge_view": row.get("judge_view"),
                    "marker_schema_version": "marker_pairwise_v1.0.0",
                    "markers": parsed["markers"],
                    "overall_marker_summary": parsed.get("overall_marker_summary", ""),
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                }
                out_f.write(json.dumps(output_row, ensure_ascii=False, sort_keys=True) + "\n")
                out_f.flush()
                wrote += 1

                if wrote % 25 == 0:
                    print(f"wrote={wrote} last_record={rid}", flush=True)

                if args.sleep_s:
                    time.sleep(args.sleep_s)

            except Exception as e:
                failures += 1
                fail_f.write(
                    json.dumps(
                        {
                            "record_id": rid,
                            "judge": args.judge_name,
                            "error": repr(e),
                            "timestamp": datetime.now(timezone.utc).isoformat(),
                        },
                        ensure_ascii=False,
                        sort_keys=True,
                    )
                    + "\n"
                )
                fail_f.flush()
                print(f"FAIL record={rid} error={e!r}", file=sys.stderr, flush=True)

    print(f"done judge={args.judge_name} wrote={wrote} failures={failures} output={out_path}", flush=True)
    return 0 if failures == 0 else 2


if __name__ == "__main__":
    raise SystemExit(main())
